import Link from "next/link";
import { posts } from "@/lib/content";
import { topics, series, site, formatDate } from "@/lib/site";
import { getSeriesPosts } from "@/lib/content";
import { PostList } from "@/components/post-list";
import { Icon } from "@/components/icon";

export default function Home() {
  const featured = posts[0];
  const featuredTopic = topics.find(t => featured.topics.includes(t.slug));
  const featuredSeries = series[0];
  const featuredSeriesPosts = featuredSeries ? getSeriesPosts(featuredSeries.slug) : [];
  const titleParts = featured.title.split(" - ");
  const featuredLead = titleParts.length > 1 ? titleParts.slice(0, -1).join(" - ") : featured.title;
  const featuredTail = titleParts.length > 1 ? titleParts.at(-1) : "";
  return <div className="container"><section className="home-hero"><div className="hero-intro"><span className="eyebrow"><span className="status-dot" /> Notes from the workbench</span><h1>Practical notes.<br /><span>Working knowledge.</span></h1><p>Code, experiments and lessons from building on<br className="desktop-break" /> Power Platform, Dynamics 365 and Azure.</p><div className="hero-links"><Link className="button button-primary" href="/blog/">Explore the writing <span>→</span></Link><a className="text-link" href={site.github}>Find me on GitHub <Icon name="arrow" /></a></div></div><div className="hero-code" aria-label="The subjects of this blog"><div className="code-window-header"><div className="window-dots"><i /><i /><i /></div><span>workbench.ts</span><Icon name="code" /></div><pre><code><span className="code-comment">// A few things I work with</span>{"\n"}<span className="code-purple">const</span> workbench = {"{"}{"\n"}  author: <span className="code-mint">'Oliver Flint'</span>,{"\n"}  focus: [{"\n"}    <span className="code-mint">'Power Platform'</span>,{"\n"}    <span className="code-mint">'Dynamics 365'</span>,{"\n"}    <span className="code-mint">'Dataverse'</span>,{"\n"}    <span className="code-mint">'Azure'</span>{"\n"}  ],{"\n"}  approach: <span className="code-mint">'Learn. Build. Share.'</span>{"\n"}{"}"};</code></pre><div className="code-window-footer"><span><span className="status-dot" /> Always learning</span><span>TypeScript</span></div></div></section>
  <section className="featured-section"><div className="section-heading"><h2><span>01</span> From the workbench</h2><Link href="/blog/">All writing <span>→</span></Link></div><div className="feature-grid"><article className="featured-card"><div className="card-top"><span className="pill">Latest article</span><span className="card-number">/ {featured.published.slice(0, 4)}</span></div><div className="eyebrow">{featuredTopic?.name || "Personal"}{featured.tags.includes("PCF") ? " · PCF" : ""}</div><h3><Link href={featured.path}>{featuredLead}{featuredTail && <span> — {featuredTail}</span>}</Link></h3><p>{featured.summary || featured.description}</p><div className="card-bottom"><span>{formatDate(featured.published)} <b>·</b> {featured.readingMinutes} min read</span><Link href={featured.path} aria-label={`Read ${featured.title}`}><Icon name="arrow" /></Link></div></article>{featuredSeries && <aside className="series-card"><div className="card-top"><span className="eyebrow">A learning path</span><Icon name="code" /></div><h3>{featuredSeries.title}</h3><p>{featuredSeries.description}</p><div className="series-steps" aria-label={`${featuredSeriesPosts.length} parts`}>{featuredSeriesPosts.map(post => <span key={post.order}>{String(post.order).padStart(2, "0")}</span>)}</div><Link className="text-link" href={`/series/${featuredSeries.slug}/`}>Explore the series <span>→</span></Link></aside>}</div></section>
  <section className="topics-section"><div className="section-heading"><h2><span>02</span> Find your thread</h2><Link href="/topics/">Browse topics <span>→</span></Link></div><div className="topic-grid">{topics.map(t => <Link key={t.slug} href={`/topics/${t.slug}/`} className="topic-card"><div><span className="topic-symbol">{t.number === "01" ? "{ }" : t.number === "02" ? "< / >" : "_ /"}</span><Icon name="arrow" /></div><h3>{t.name}</h3><p>{t.short}</p><span className="topic-count">{posts.filter(p => p.topics.includes(t.slug)).length} {posts.filter(p => p.topics.includes(t.slug)).length === 1 ? "article" : "articles"}</span></Link>)}</div></section>
  <section className="recent-section"><div className="section-heading"><h2><span>03</span> More from the archive</h2><Link href="/blog/">View all <span>→</span></Link></div><PostList posts={posts.slice(1, 5)} /></section>
  <section className="about-strip"><span className="small-mark">of.</span><div><h2>A little context.</h2><p>I'm Oliver — a Dynamics 365 solution architect, tech enthusiast, and a believer in sharing what you learn.</p></div><Link className="text-link" href="/about/">More about me <Icon name="arrow" /></Link></section></div>;
}
